[package]
name = "server_net"
version = "0.1.0"
edition = "2024"


[features]
default = ["gui", "server", "netcode", "udp"]
gui = ["lightyear_examples_common/gui"]
server = ["lightyear_examples_common/server"]
netcode = ["lightyear_examples_common/netcode"]
udp = ["lightyear_examples_common/udp"]
# steam = ["lightyear_examples_common/steam"]


[dependencies]
lightyear = { version = "0.24.2", features = [
 "interpolation",
 "prediction",
 "replication",
 "input_native",
] }
lightyear_examples_common = { path = "../common" }
# serde.workspace = true


bincode = { version = "2.0.1", default-features = false, features = [
 "serde",
 "alloc",
] }
bytes = { version = "1.8", default-features = false, features = ["serde"] }
serde = { version = "1", default-features = false, features = [
 "alloc",
 "derive",
] }


bevy = "0.16"
bevy-inspector-egui = "=0.33.1"
bevy_egui = "0.36.0"
bevy_console = "0.14.1"
